config/routes.rb
Rails.application.routes.draw do
  root 'dictionaries#index'

  resources :dictionaries do
    collection do
      post :import_words
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dictionary.rb
class Dictionary < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dictionaries_controller.rb
class DictionariesController < ApplicationController
  def index
    @word_counts ||= Dictionary.count

    unless params[:date].nil? || params[:date].blank?
      @analyzed_date = params[:date]
      flash.now[:response] = "Wyszukiwane słowo #{potential_word} #{checkout_word ? "Istnieje!" : "Nie istnieje :("}"
    end
  end

  def import_words
    if params[:csv].present?
      begin
        CsvImportService.new(params[:csv].path).call
        flash[:response] = "Słowa załadowane!"
        redirect_to root_path
      rescue
        flash[:response] = "Coś poszło nie tak"
        redirect_to root_path
      end
    end
  end

  private

  attr_reader :analyzed_date

  def ensure_digits
    analyzed_date.to_i
  end

  def potential_word
    ensure_digits.to_s(36)
  end

  def checkout_word
    Dictionary.find_by(word: potential_word)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dictionaries_helper.rb
module DictionariesHelper
end

app/views/dictionaries/index.html.erb
<h1><%= link_to "Analizator dat urodzin", root_path, class: "h1"%></h1>
<p>Wpisz swoją datę urodzenia poniżej</p>

<%= form_tag(root_path, method: :get) do %>
  <%= text_field_tag :date %>
  <%= submit_tag "Sprawdź!" %>
<% end %>

<% flash.each do |a, alert| %>
  <%= alert %>
<% end %>

<br / >

<% if @word_counts.zero? %>
  <%= form_tag import_words_dictionaries_path, multipart: :true do %>
    <%= file_field_tag :csv, accept: 'text/csv', class: "form-control padding-lg" %><br>
    <%= submit_tag "Wczytaj plik CSV", class: "btn btn-lg btn-block btn-success" %>
  <% end %>
<% else %>
  Baza danych zawiera <%= @word_counts %> słów!
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DateAnalysis</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>